-- AlterTable
ALTER TABLE "User" ALTER COLUMN "address" SET DEFAULT '',
ALTER COLUMN "avatar" SET DEFAULT '',
ALTER COLUMN "cover_photo" SET DEFAULT '',
ALTER COLUMN "created_at" DROP NOT NULL,
ALTER COLUMN "roles" DROP NOT NULL,
ALTER COLUMN "status" DROP NOT NULL;
